version: '3.8'

services:
  pgdb:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_DB: to-doListDatabase
      POSTGRES_USER: to-doListUser
      POSTGRES_PASSWORD: alexyegane2002
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: on-failure
    
    environment:
      SECRET_KEY: 'qwertyhnkpiygdgfrs54'
      DB_NAME: to-doListDatabase
      DB_USER: to-doListUser
      DB_PASSWORD: alexyegane2002
      DB_HOST: pgdb
      DB_PORT: "5432"
    volumes:
      - .:/app
    ports:
      - "8000:8000"

    depends_on:
      - pgdb


volumes:
  postgres_data:
    driver: local
