version: '3.8'

services:
  db:
    image: postgresql:16
    environment:
      POSTGRES_DB: to-doListDatabase
      POSTGRES_USER: to-doListUser
      POSTGRES_PASSWORD: alexyegane2002
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - to-do-list

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - to-do-list
  
networks:
  - to-do-list