# Generated by Django 4.2.3 on 2023-07-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="due_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="tasks",
            name="info",
            field=models.TextField(default="default value"),
        ),
        migrations.AddField(
            model_name="tasks",
            name="title_tag",
            field=models.CharField(default="uncategorized", max_length=250),
        ),
    ]
