# Generated by Django 4.2.3 on 2023-07-22 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("page", "0002_tasks_due_date_tasks_info_tasks_title_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="completed",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="due_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="info",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="title_tag",
            field=models.CharField(max_length=250),
        ),
    ]
