# Generated by Django 4.2.5 on 2023-09-14 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_profile_contactinformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinformation",
            name="user_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="page.profile"
            ),
        ),
    ]
