# Generated by Django 4.2.3 on 2023-07-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0003_tasks_user_alter_tasks_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="due_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="info",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="title_tag",
            field=models.CharField(default="Uncategorized", max_length=250),
        ),
    ]
